package com.example.boostmode.database

import com.example.boostmode.database.entity.CircuitEntity
import com.example.boostmode.database.entity.DriverEntity
import com.example.boostmode.database.entity.RaceEntity

object DatabaseSeeder {

    fun getRaces(): List<RaceEntity> = listOf(
        RaceEntity("australia", "Australia", "Melbourne", "01", "06-08 mar", "previous"),
        RaceEntity("china", "China", "Shanghai", "02", "13-15 mar", "previous"),
        RaceEntity("japan", "Japan", "Suzuka", "03", "27-29 mar", "previous"),
        RaceEntity("miami", "Miami", "Miami", "04", "01-03 may", "current"),
        RaceEntity("canada", "Canada", "Montreal", "05", "22-24 may", "upcoming"),
        RaceEntity("monaco", "Monaco", "Monte Carlo", "06", "05-07 jun", "upcoming"),
        RaceEntity("barcelona", "Spain", "Barcelona", "07", "19-21 jun", "upcoming"),
        RaceEntity("madrid", "Spain", "Madrid", "08", "03-05 jul", "upcoming"),
        RaceEntity("britain", "Great Britain", "Silverstone", "09", "17-19 jul", "upcoming"),
        RaceEntity("belgium", "Belgium", "Spa", "10", "31 jul-02 aug", "upcoming"),
        RaceEntity("hungary", "Hungary", "Budapest", "11", "07-09 aug", "upcoming"),
        RaceEntity("netherlands", "Netherlands", "Zandvoort", "12", "21-23 aug", "upcoming"),
        RaceEntity("italy", "Italy", "Monza", "13", "04-06 sep", "upcoming"),
        RaceEntity("azerbaijan", "Azerbaijan", "Baku", "14", "19 sep", "upcoming"),
        RaceEntity("singapore", "Singapore", "Singapore", "15", "02-04 oct", "upcoming"),
        RaceEntity("usa", "USA", "Austin", "16", "23-25 oct", "upcoming"),
        RaceEntity("mexico", "Mexico", "Mexico City", "17", "30 oct-01 nov", "upcoming"),
        RaceEntity("brazil", "Brazil", "São Paulo", "18", "13-15 nov", "upcoming"),
        RaceEntity("lasvegas", "Las Vegas", "Las Vegas", "19", "21-22 nov", "upcoming"),
        RaceEntity("qatar", "Qatar", "Lusail", "20", "28-30 nov", "upcoming"),
        RaceEntity("abudhabi", "Abu Dhabi", "Yas Marina", "21", "04-06 dec", "upcoming")
    )

    fun getDrivers(): List<DriverEntity> = listOf(
        // McLaren
        DriverEntity("norris", "Lando", "Norris", "McLaren", "4"),
        DriverEntity("piastri", "Oscar", "Piastri", "McLaren", "81"),
        // Mercedes
        DriverEntity("russell", "George", "Russell", "Mercedes", "63"),
        DriverEntity("antonelli", "Kimi", "Antonelli", "Mercedes", "12"),
        // Red Bull
        DriverEntity("verstappen", "Max", "Verstappen", "Red Bull", "1"),
        DriverEntity("hadjar", "Isack", "Hadjar", "Red Bull", "6"),
        // Ferrari
        DriverEntity("leclerc", "Charles", "Leclerc", "Ferrari", "16"),
        DriverEntity("hamilton", "Lewis", "Hamilton", "Ferrari", "44"),
        // Williams
        DriverEntity("sainz", "Carlos", "Sainz", "Williams", "55"),
        DriverEntity("albon", "Alexander", "Albon", "Williams", "23"),
        // Racing Bulls
        DriverEntity("lawson", "Liam", "Lawson", "Racing Bulls", "30"),
        DriverEntity("lindblad", "Arvid", "Lindblad", "Racing Bulls", "62"),
        // Aston Martin
        DriverEntity("alonso", "Fernando", "Alonso", "Aston Martin", "14"),
        DriverEntity("stroll", "Lance", "Stroll", "Aston Martin", "18"),
        // Haas
        DriverEntity("ocon", "Esteban", "Ocon", "Haas", "31"),
        DriverEntity("bearman", "Oliver", "Bearman", "Haas", "87"),
        // Audi
        DriverEntity("hulkenberg", "Nico", "Hülkenberg", "Audi", "27"),
        DriverEntity("bortoleto", "Gabriel", "Bortoleto", "Audi", "5"),
        // Alpine
        DriverEntity("gasly", "Pierre", "Gasly", "Alpine", "10"),
        DriverEntity("colapinto", "Franco", "Colapinto", "Alpine", "43"),
        // Cadillac
        DriverEntity("perez", "Sergio", "Pérez", "Cadillac", "11"),
        DriverEntity("bottas", "Valtteri", "Bottas", "Cadillac", "77")
    )

    fun getCircuits(): List<CircuitEntity> = listOf(
        CircuitEntity(
            raceId = "australia",
            location = "Melbourne, Australia",
            opened = "1953",
            firstF1Gp = "1996",
            turns = "16",
            length = "5.278 km",
            laps = "58",
            about = "The Albert Park Circuit is a street circuit in Melbourne, Australia. Located around a lake in Albert Park, it has hosted the Australian Grand Prix since 1996 and traditionally opens the F1 season.",
            lapTimeRecord = "1:20.235",
            driver = "Charles Leclerc",
            car = "Ferrari SF-24",
            year = "2024",
            avgSpeed = "236.1 km/h"
        ),
        CircuitEntity(
            raceId = "china",
            location = "Shanghai, China",
            opened = "2004",
            firstF1Gp = "2004",
            turns = "16",
            length = "5.451 km",
            laps = "56",
            about = "The Shanghai International Circuit is a purpose-built racing venue designed by Hermann Tilke. The circuit features a unique spiral-shaped infield section and long straight.",
            lapTimeRecord = "1:32.238",
            driver = "Michael Schumacher",
            car = "Ferrari F2004",
            year = "2004",
            avgSpeed = "212.8 km/h"
        ),
        CircuitEntity(
            raceId = "japan",
            location = "Suzuka, Japan",
            opened = "1962",
            firstF1Gp = "1987",
            turns = "18",
            length = "5.807 km",
            laps = "53",
            about = "Suzuka Circuit is a figure-eight-shaped racing circuit in Japan. It is renowned for its technical layout featuring fast corners, chicanes, and the famous 130R corner. One of the most beloved circuits on the calendar.",
            lapTimeRecord = "1:30.983",
            driver = "Lewis Hamilton",
            car = "Mercedes W05",
            year = "2024",
            avgSpeed = "230.5 km/h"
        ),
        CircuitEntity(
            raceId = "miami",
            location = "Miami, USA",
            opened = "2022",
            firstF1Gp = "2022",
            turns = "19",
            length = "5.412 km",
            laps = "57",
            about = "The Miami International Autodrome is a street circuit built around the Hard Rock Stadium complex. It debuted in 2022 and quickly became a fan favourite with its vibrant atmosphere.",
            lapTimeRecord = "1:29.708",
            driver = "Max Verstappen",
            car = "Red Bull RB20",
            year = "2024",
            avgSpeed = "219.4 km/h"
        ),
        CircuitEntity(
            raceId = "monaco",
            location = "Monte Carlo, Monaco",
            opened = "1929",
            firstF1Gp = "1950",
            turns = "19",
            length = "3.337 km",
            laps = "78",
            about = "The Circuit de Monaco is the most glamorous race on the F1 calendar, run through the narrow streets of Monte Carlo. It is the slowest and most prestigious Grand Prix, known for its tight barriers and zero margin for error.",
            lapTimeRecord = "1:10.166",
            driver = "Lewis Hamilton",
            car = "Mercedes W12",
            year = "2021",
            avgSpeed = "157.2 km/h"
        ),
        CircuitEntity(
            raceId = "italy",
            location = "Monza, Italy",
            opened = "1922",
            firstF1Gp = "1950",
            turns = "11",
            length = "5.793 km",
            laps = "53",
            about = "The Autodromo Nazionale Monza, known as the Temple of Speed, is the oldest purpose-built racing circuit still in use. Located in a royal park north of Milan, it features long straights and high-speed corners.",
            lapTimeRecord = "1:21.046",
            driver = "Rubens Barrichello",
            car = "Ferrari F2004",
            year = "2004",
            avgSpeed = "247.6 km/h"
        ),
        CircuitEntity(
            raceId = "netherlands",
            location = "Zandvoort, Netherlands",
            opened = "1948",
            firstF1Gp = "1952",
            turns = "14",
            length = "4.259 km",
            laps = "72",
            about = "Circuit Zandvoort is nestled among the sand dunes of the Dutch coast. Returned to the F1 calendar in 2021, it features iconic banked corners and passionate orange-clad Dutch fans.",
            lapTimeRecord = "1:11.097",
            driver = "Max Verstappen",
            car = "Red Bull RB19",
            year = "2023",
            avgSpeed = "196.8 km/h"
        ),
        CircuitEntity(
            raceId = "britain",
            location = "Silverstone, United Kingdom",
            opened = "1948",
            firstF1Gp = "1950",
            turns = "18",
            length = "5.891 km",
            laps = "52",
            about = "Silverstone Circuit hosted the very first Formula 1 World Championship race in 1950. Known for its fast and flowing layout, Copse and Maggotts-Becketts sections are among the most challenging in F1.",
            lapTimeRecord = "1:27.097",
            driver = "Max Verstappen",
            car = "Red Bull RB19",
            year = "2023",
            avgSpeed = "240.5 km/h"
        ),
        CircuitEntity(
            raceId = "belgium",
            location = "Spa-Francorchamps, Belgium",
            opened = "1921",
            firstF1Gp = "1950",
            turns = "19",
            length = "7.004 km",
            laps = "44",
            about = "Circuit de Spa-Francorchamps is set in the Ardennes forest and is widely regarded as the greatest racing circuit in the world. The iconic Eau Rouge-Raidillon complex is one of the most thrilling sequences in motorsport.",
            lapTimeRecord = "1:41.252",
            driver = "Valtteri Bottas",
            car = "Mercedes W11",
            year = "2020",
            avgSpeed = "234.3 km/h"
        ),
        CircuitEntity(
            raceId = "canada",
            location = "Montreal, Canada",
            opened = "1978",
            firstF1Gp = "1978",
            turns = "14",
            length = "4.361 km",
            laps = "70",
            about = "Circuit Gilles Villeneuve is a street circuit on the Île Notre-Dame in Montreal. Named after the legendary Ferrari driver, it features long straights and a famous wall at the final chicane nicknamed The Wall of Champions.",
            lapTimeRecord = "1:13.078",
            driver = "Valtteri Bottas",
            car = "Mercedes W11",
            year = "2019",
            avgSpeed = "215.0 km/h"
        ),
        CircuitEntity(
            raceId = "barcelona",
            location = "Montmeló, Spain",
            opened = "1991",
            firstF1Gp = "1991",
            turns = "16",
            length = "4.675 km",
            laps = "66",
            about = "Circuit de Barcelona-Catalunya is a technically demanding circuit near Barcelona. A favourite for pre-season testing, it rewards aerodynamic efficiency and tyre management over a lap.",
            lapTimeRecord = "1:16.330",
            driver = "Max Verstappen",
            car = "Red Bull RB16B",
            year = "2021",
            avgSpeed = "210.5 km/h"
        ),
        CircuitEntity(
            raceId = "madrid",
            location = "Madrid, Spain",
            opened = "2026",
            firstF1Gp = "2026",
            turns = "20",
            length = "5.500 km",
            laps = "57",
            about = "The new Madrid Street Circuit debuted in 2026 around the IFEMA convention centre. A brand new addition to the calendar, it brings Formula 1 to the Spanish capital for the first time.",
            lapTimeRecord = "N/A",
            driver = "N/A",
            car = "N/A",
            year = "2026",
            avgSpeed = "N/A"
        ),
        CircuitEntity(
            raceId = "hungary",
            location = "Budapest, Hungary",
            opened = "1986",
            firstF1Gp = "1986",
            turns = "14",
            length = "4.381 km",
            laps = "70",
            about = "The Hungaroring is a tight and twisty circuit near Budapest, often called the Monaco of Hungary. Its narrow layout makes overtaking notoriously difficult, placing a premium on qualifying performance.",
            lapTimeRecord = "1:16.627",
            driver = "Lewis Hamilton",
            car = "Mercedes W11",
            year = "2020",
            avgSpeed = "195.0 km/h"
        ),
        CircuitEntity(
            raceId = "azerbaijan",
            location = "Baku, Azerbaijan",
            opened = "2016",
            firstF1Gp = "2016",
            turns = "20",
            length = "6.003 km",
            laps = "51",
            about = "The Baku City Circuit runs through the historic streets of Azerbaijan's capital. Combining a castle section with a long 2 km straight, it consistently produces action-packed and unpredictable races.",
            lapTimeRecord = "1:43.009",
            driver = "Charles Leclerc",
            car = "Ferrari SF-23",
            year = "2023",
            avgSpeed = "210.1 km/h"
        ),
        CircuitEntity(
            raceId = "singapore",
            location = "Singapore",
            opened = "2008",
            firstF1Gp = "2008",
            turns = "19",
            length = "4.940 km",
            laps = "62",
            about = "Marina Bay Street Circuit is the home of F1's first night race. Illuminated by over 1,500 lights, the circuit weaves through Singapore's financial district and is one of the most physically demanding on the calendar.",
            lapTimeRecord = "1:30.984",
            driver = "Carlos Sainz",
            car = "Ferrari SF-23",
            year = "2023",
            avgSpeed = "182.3 km/h"
        ),
        CircuitEntity(
            raceId = "usa",
            location = "Austin, USA",
            opened = "2012",
            firstF1Gp = "2012",
            turns = "20",
            length = "5.513 km",
            laps = "56",
            about = "Circuit of the Americas is the first purpose-built F1 circuit in the United States. Its layout was inspired by classic F1 venues, featuring significant elevation changes and a sweeping Turn 1 hairpin.",
            lapTimeRecord = "1:36.169",
            driver = "Charles Leclerc",
            car = "Ferrari SF-24",
            year = "2024",
            avgSpeed = "206.0 km/h"
        ),
        CircuitEntity(
            raceId = "mexico",
            location = "Mexico City, Mexico",
            opened = "1962",
            firstF1Gp = "1963",
            turns = "17",
            length = "4.304 km",
            laps = "71",
            about = "Autódromo Hermanos Rodríguez sits at 2,285 metres above sea level, the highest altitude on the F1 calendar. The thin air drastically reduces aerodynamic downforce and engine power, creating unique engineering challenges.",
            lapTimeRecord = "1:17.774",
            driver = "Valtteri Bottas",
            car = "Mercedes W11",
            year = "2021",
            avgSpeed = "199.7 km/h"
        ),
        CircuitEntity(
            raceId = "brazil",
            location = "São Paulo, Brazil",
            opened = "1940",
            firstF1Gp = "1973",
            turns = "15",
            length = "4.309 km",
            laps = "71",
            about = "Autódromo José Carlos Pace, known as Interlagos, is one of the most beloved circuits in F1. Its anti-clockwise layout, steep elevation changes and notoriously unpredictable weather produce spectacular racing.",
            lapTimeRecord = "1:07.281",
            driver = "Valtteri Bottas",
            car = "Mercedes W09",
            year = "2018",
            avgSpeed = "231.0 km/h"
        ),
        CircuitEntity(
            raceId = "lasvegas",
            location = "Las Vegas, USA",
            opened = "2023",
            firstF1Gp = "2023",
            turns = "17",
            length = "6.201 km",
            laps = "50",
            about = "The Las Vegas Strip Circuit is a night street race running past the iconic casinos and hotels of the Strip. One of the longest laps on the calendar, it combines high-speed straights with tight chicanes.",
            lapTimeRecord = "1:31.877",
            driver = "Carlos Sainz",
            car = "Ferrari SF-23",
            year = "2023",
            avgSpeed = "241.6 km/h"
        ),
        CircuitEntity(
            raceId = "qatar",
            location = "Lusail, Qatar",
            opened = "2004",
            firstF1Gp = "2021",
            turns = "16",
            length = "5.380 km",
            laps = "57",
            about = "Lusail International Circuit is a purpose-built venue near Doha, originally designed for MotoGP. Its flowing high-speed layout under floodlights and extreme heat make it a demanding physical challenge for drivers.",
            lapTimeRecord = "1:20.456",
            driver = "Max Verstappen",
            car = "Red Bull RB19",
            year = "2023",
            avgSpeed = "240.6 km/h"
        ),
        CircuitEntity(
            raceId = "abudhabi",
            location = "Yas Marina, Abu Dhabi",
            opened = "2009",
            firstF1Gp = "2009",
            turns = "16",
            length = "5.281 km",
            laps = "58",
            about = "Yas Marina Circuit on Yas Island is the traditional season finale venue. The circuit uniquely passes under the W Hotel and along the marina, combining a modern layout with a spectacular twilight race atmosphere.",
            lapTimeRecord = "1:26.103",
            driver = "Max Verstappen",
            car = "Red Bull RB16B",
            year = "2021",
            avgSpeed = "220.5 km/h"
        )
    )
}